settings:
  debug: false
  bossbar:
    enabled: true
    color: "BLUE"
    fade_time: 5
    style: SOLID
    show-progress: true
  gui:
    title: "Tutorial Quests"
    size: 27
    show-progress: true
  worldguard-support: true
  messages:
    prefix: "&8[&bTutorial&8] &7"
    quest-complete: "&aQuest completed! &7Received rewards:"
    quest-progress: "&7Progress: &b%progress%&7/&b%total%"
    quest-locked: "&cComplete previous quests first!"